### ISSUE TITLE
ERROR: Cannot locate specified Dockerfile: Dockerfile

### ISSUE THREAD

**Issue by j2l** [sscholl/biblebot#7]
Hey, great project!
After I pulled biblebot and mysql I got this error:
```
docker-compose up -d
Pulling biblebotdb (mysql:)...
latest: Pulling from library/mysql
177e7ef0df69: Pull complete
cac25352c4c8: Pull complete
8585afabb40a: Pull complete
1e4af4996053: Pull complete
c326522894da: Pull complete
9020d6b6b171: Pull complete
55eb37ec6e5f: Pull complete
37f3f3d72fbd: Pull complete
03f098d64268: Pull complete
46a52a54cfe9: Pull complete
202bc662895d: Pull complete
46014f07b258: Pull complete
Building biblebot
ERROR: Cannot locate specified Dockerfile: Dockerfile
```
I had to adapt ports since I already run other containers, including rocketchat
```
  biblebot:
    build: .
    environment:
      - SPRING_DATASOURCE_USERNAME=biblebot
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:mysql://biblebotdb:3306/biblebot?autoReconnect=true&characterEncoding=utf8&useSSL=false
      - BIBLEBOT_INTEGRATION_ACTIVE=true
      - BIBLEBOT_INTEGRATION_HOST=biblebot
      - BIBLEBOT_INTEGRATION_PORT=8082
      - BIBLEBOT_API_HOST=rocketchat
      - BIBLEBOT_API_PORT=3000
      - BIBLEBOT_API_USER=bot
      - BIBLEBOT_API_PASSWORD=pass
      - BIBLEREADINGPLAN_POSTSERVICE_CRON=0 0 * * * *
    links:
      - rocketchat
      - biblebotdb
    ports:
      - 8082:8082
    networks:
      - vpcbr

  biblebotdb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: unusedpassword
      MYSQL_DATABASE: biblebot
      MYSQL_USER: biblebot
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - vpcbr
```
The missing Dockerfile is within the biblebot image, right?

BTW, what are the Bible versions you offer?

Thx
